[tool.poetry]
name = "python-package"
version = "1.0.11"
description = ""
authors = ["JCayllahuaG <u202019558@upc.edu.pe>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
