name: Upload Artifacts to Artifactory Repository Releases Section

on:
  release:
    types: [published, created]
  workflow_dispatch:
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies & poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Install toml module
      run: |
        poetry add toml --dev

    - name: Get package name
      id: package_name
      run: |
        PACKAGE_NAME=$(poetry run python -c "import toml; print(toml.load('pyproject.toml')['tool']['poetry']['name'])")
        echo "package_name=${PACKAGE_NAME}" >> $GITHUB_ENV
        
    - name: Print extracted package name
      run: echo "Package name is ${{ env.package_name }}"

    - name: Get package version
      id: package_version
      run: |
        PACKAGE_VERSION=$(poetry version | cut -d' ' -f2)
        echo "package_version=${PACKAGE_VERSION}" >> $GITHUB_ENV

    - name: Print extracted package version
      run: echo "Package version is ${{ env.package_version }}"

    - name: Build the package
      run: |
        poetry build

    - name: List dist
      run: |
        ls

    - name: Create Release in Artifactory Repository
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.package_version }}
        artifacts: "dist/*.tar.gz, dist/*.whl"
        name: "${{env.package_name}} Release ${{ env.package_version }}"
        draft: false
        prerelease: false
        repo: package-artifacts
        owner: testing-organization-jcayllahua
        token: ${{ secrets.GH_PAT }}
        
